### ISSUE TITLE
VATSpy.Dat Exception: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by jackscrj** [vatsimnetwork/vatspy-data-project#23]
Vatspy hits exception when using the VATSpy.dat file provided with this repo. Note that FIRBoundaries works fine. 

![image](https://user-images.githubusercontent.com/5572570/76365203-195d1500-62fd-11ea-976f-c8e60da17500.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at VATSpy.MainForm.RepopulateFIRControllersGrid()
   at VATSpy.MainForm.ShowFIR(String firICAO, Boolean selectTab)
   at VATSpy.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9043 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
VATSpy
    Assembly Version: 1.0.3719.41261
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VATSpy/VATSpy.exe
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9042 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9031 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9031 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9038 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9031 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
giaxk1wj
    Assembly Version: 1.0.3719.41261
    Win32 Version: 2.0.50727.9042 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Tao.Platform.Windows
    Assembly Version: 1.0.0.5
    Win32 Version: 1.0.0.5
    CodeBase: file:///C:/Program%20Files%20(x86)/VATSpy/Tao.Platform.Windows.DLL
----------------------------------------
Tao.OpenGl
    Assembly Version: 2.1.0.12
    Win32 Version: 2.1.0.12
    CodeBase: file:///C:/Program%20Files%20(x86)/VATSpy/Tao.OpenGl.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by nepetadosmil** [comment]
Is this still an issue? Have you confirmed it's actually an issue with VATSpy.dat? How?
Can you try with [all the past versions](https://github.com/vatsimnetwork/vatspy-data-project/commits/master/VATSpy.dat) and let us know at which point it stops working?

**Comment by jackscrj** [comment]
The VATSpy.dat file appears not to be the source of the issue. I deleted my VATSpyConfig file and let it regenerate with your VATSpy.dat and it ended up working. It must have been stuck on an old FIR for Last viewed or something of that sort that was no longer present. Thanks
